##' Paved Road dust generation
##' 
##' A function to estimate dust generated by paved road in quarry site.
##' 
##' @param quarryInput data frame containing column names: quarryProduction - quarry production tonne per hour,
##' blastingFreq - blasting frequency per month, areaBlasted - area blasted (km. sq), blasthole - average of depth of blast hole (m), drillhole - drilling hole per month,
##' moisture - percentage of moisture content, silt - percentage of silt content, unpavedDist - unpaved road distant (KM), pavedDist - paved road distance (KM), 
##' unpavedVehicle - number of vehicle count travel using unpaved road per month, pavedVehicle - number of vehicle count travel using paved road per month, 
##' nPrimary - number of primary crusher, nSecondary - number of secondary crusher, nTertiary - number of tertiary crusher, nScreen - number of screen.
##'
##' @param particleSize particle size of dust deposited rate. The default value is "tsp" for total suspended solid 
##' and other available particle size is "pm10" for particulate matter <10 micron. 
##' 
##' @param vehicleTravelled number of vehicle used the road per month, use the default to read pavedVehicle value inside quarryInput dataframe
##' @param roadDistance total paved road in the quarry (KM), use the default to read pavedDist value inside quarryInput dataframe
##' @param sp a constant value. Default value is 5.
##' @param vehicleWeight average vehicle weight (tonne). The dafaults is 10.
##'
##' @export
##' 
##' @author Zul Fadhli & Dr. Izhar Abadi
##' 
##' @examples 
##' #demo
##' pavedRoad <- function(quarryInput, particleSize = "tsp", sp = 5, vehicleWeight = 10)

pavedRoad <- function(quarryInput, particleSize = "tsp",
                        vehicleTravelled = quarryInput$pavedVehicle, roadDistance = quarryInput$pavedDist,
                        sp = 5, vehicleWeight = 10)

{
  quarryInput <- quarryInput

  if(particleSize == "tsp") {
    kpave = 24
  }else if (particleSize == "pm10"){
    kpave = 4.6
  }

  sp <- 5
  vehicleWeight <- 10

  kpave*(sp/2)^0.65*(vehicleWeight/3)^1.5*vehicleTravelled*roadDistance/roadDistance/1000*12/1000/1000


}
